
时间：2017-06-20 09:18:36,817 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：852749 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.list.getSub(Int32 s) 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\list.cs:行号 50
   在 X.App.Apis.mgr.paper.list.<Execute>b__20_0(x_paper o) 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\list.cs:行号 31
   在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Json.Serialization.JsonArrayContract.CreateWrapper(Object list)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   在 X.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   在 X.Core.Utility.Serialize.ToJson(Object o, Boolean ignore) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 26
   在 X.Core.Utility.Serialize.ToJson(Object o) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 18
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 09:24:45,518 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"缺少参数 代号","code":"0x0003"} 
时间：1221450 

时间：2017-06-20 09:24:52,329 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"缺少参数 代号","code":"0x0003"} 
时间：1228261 

时间：2017-06-20 09:25:08,317 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：1244249 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.Data.x_dict.<>c__DisplayClass3_1.<GetDictList>b__2(x_dict o) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 88
   在 System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 86
   在 X.Web.XFace.GetDictList(String code, String upval) 位置 D:\Pro\x.xue\src\Web\X.Web\XFace.cs:行号 175
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\com\dict.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 09:29:00,970 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4197 
System.InvalidOperationException: 可为空的对象必须具有一个值。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Nullable`1.get_Value()
   在 X.App.Views.mgr.subject.select.<>c__DisplayClass4_0.<tree_LoadList>b__1(x_dict m) 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\subject\select.cs:行号 34
   在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.App.Views.mgr.subject.select.tree_LoadList(Object id) 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\subject\select.cs:行号 34
   在 X.Data.XTree.getChild(TreeNode n, Int32 d) 位置 D:\Pro\x.xue\src\Xc\Data\XTree.cs:行号 63
   在 X.Data.XTree.InitTree(String title, Int32 deep) 位置 D:\Pro\x.xue\src\Xc\Data\XTree.cs:行号 27
   在 X.App.Views.mgr.subject.select.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\subject\select.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 09:32:45,291 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：130254 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.Data.x_dict.<>c__DisplayClass3_1.<GetDictList>b__2(x_dict o) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 88
   在 System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 86
   在 X.Web.XFace.GetDictList(String code, String upval) 位置 D:\Pro\x.xue\src\Web\X.Web\XFace.cs:行号 175
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\com\dict.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 09:36:47,739 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：372702 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.Data.x_dict.<>c__DisplayClass3_1.<GetDictList>b__2(x_dict o) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 88
   在 System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 86
   在 X.Web.XFace.GetDictList(String code, String upval) 位置 D:\Pro\x.xue\src\Web\X.Web\XFace.cs:行号 175
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\com\dict.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 09:37:48,922 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：14446 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.Data.x_dict.<>c__DisplayClass3_1.<GetDictList>b__2(x_dict o) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 88
   在 System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 86
   在 X.Web.XFace.GetDictList(String code, String upval) 位置 D:\Pro\x.xue\src\Web\X.Web\XFace.cs:行号 175
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\com\dict.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 09:38:21,629 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：47153 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.Data.x_dict.<>c__DisplayClass3_1.<GetDictList>b__2(x_dict o) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 88
   在 System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 86
   在 X.Web.XFace.GetDictList(String code, String upval) 位置 D:\Pro\x.xue\src\Web\X.Web\XFace.cs:行号 175
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\com\dict.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 10:30:22,215 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：792514 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.paper.edit.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\paper\edit.cs:行号 27
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 10:30:26,149 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：796447 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.paper.edit.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\paper\edit.cs:行号 27
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 10:30:26,713 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：797012 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.paper.edit.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\paper\edit.cs:行号 27
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 10:31:24,301 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：41383 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.paper.edit.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 10:56:33,269 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：46802 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInvocation(InvocationExpression invoke)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitContains(Expression sequence, Expression value)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSelect(Expression sequence, LambdaExpression selector)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   在 System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Json.Serialization.JsonArrayContract.CreateWrapper(Object list)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   在 X.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   在 X.Core.Utility.Serialize.ToJson(Object o, Boolean ignore) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 26
   在 X.Core.Utility.Serialize.ToJson(Object o) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 18
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:11:24,424 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：229 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.mgr.paper.edit.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\paper\edit.cs:行号 40
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:11:58,183 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：17518 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.mgr.paper.edit.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\paper\edit.cs:行号 40
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:31:31,987 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：281534 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInvocation(InvocationExpression invoke)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitContains(Expression sequence, Expression value)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSelect(Expression sequence, LambdaExpression selector)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   在 System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Json.Serialization.JsonArrayContract.CreateWrapper(Object list)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   在 X.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   在 X.Core.Utility.Serialize.ToJson(Object o, Boolean ignore) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 26
   在 X.Core.Utility.Serialize.ToJson(Object o) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 18
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:31:56,607 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：306154 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInvocation(InvocationExpression invoke)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitContains(Expression sequence, Expression value)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSelect(Expression sequence, LambdaExpression selector)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   在 System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Json.Serialization.JsonArrayContract.CreateWrapper(Object list)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   在 X.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   在 X.Core.Utility.Serialize.ToJson(Object o, Boolean ignore) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 26
   在 X.Core.Utility.Serialize.ToJson(Object o) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 18
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:32:57,051 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：366598 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInvocation(InvocationExpression invoke)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitContains(Expression sequence, Expression value)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSelect(Expression sequence, LambdaExpression selector)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   在 System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Json.Serialization.JsonArrayContract.CreateWrapper(Object list)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 X.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   在 X.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   在 X.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   在 X.Core.Utility.Serialize.ToJson(Object o, Boolean ignore) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 26
   在 X.Core.Utility.Serialize.ToJson(Object o) 位置 D:\Pro\x.xue\src\Xc\Core\Utility\Serialize.cs:行号 18
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:34:55,383 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：484930 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:35:39,653 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：529200 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:42:09,576 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4590 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:42:12,685 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：7699 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:42:30,051 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：25064 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:44:36,003 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：151017 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:44:59,163 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：174176 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:53:36,111 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：539 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:56:30,101 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：34533 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 11:57:00,583 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：65014 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:03:27,390 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：451821 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:05:31,429 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：575860 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:06:08,102 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：612533 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:06:56,913 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：661344 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:07:44,825 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：709257 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:10:10,559 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：854990 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 12:51:02,734 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：3307165 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 13:41:52,741 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6357172 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 13:42:17,541 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：6381972 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:03:32,423 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：7656854 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.save.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\save.cs:行号 69
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:08:51,438 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"参数不正确 试卷ID的值要大于1","code":"0x0004"} 
时间：172 

时间：2017-06-20 14:10:06,209 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：74943 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:10:11,176 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T试卷参数丢失)","code":"T试卷参数丢失"} 
时间：79909 

时间：2017-06-20 14:10:28,371 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：97105 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:10:45,608 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：114341 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:11:22,626 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：151359 

时间：2017-06-20 14:11:48,488 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：177221 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:12:36,153 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：224886 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:12:46,681 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：235414 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:13:09,236 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：257970 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.mgr.paper.question.qlist.Execute() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Apis\mgr\paper\question\qlist.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 14:20:52,806 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：78798 

时间：2017-06-20 14:23:14,303 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：220295 

时间：2017-06-20 14:23:46,458 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：252450 

时间：2017-06-20 14:29:39,246 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：9470 

时间：2017-06-20 14:33:35,780 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：14399 

时间：2017-06-20 14:34:38,360 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(试卷参数丢失，请从试卷管理进入)","code":"试卷参数丢失，请从试卷管理进入"} 
时间：5339 

时间：2017-06-20 14:41:40,707 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":" ","code":"0x0022"} 
时间：242509 

时间：2017-06-20 14:43:21,781 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"参数不正确 ","code":"0x0004"} 
时间：257 

时间：2017-06-20 14:45:06,818 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"参数不正确 ","code":"0x0004"} 
时间：264 

时间：2017-06-20 14:45:40,426 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：259 

时间：2017-06-20 14:47:24,608 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：104440 

时间：2017-06-20 14:48:41,994 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：257 

时间：2017-06-20 14:49:58,285 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：76548 

时间：2017-06-20 14:49:59,397 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：77661 

时间：2017-06-20 14:51:09,418 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：147681 

时间：2017-06-20 14:51:44,383 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：255 

时间：2017-06-20 14:51:46,902 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：2773 

时间：2017-06-20 14:52:30,402 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：312 

时间：2017-06-20 14:52:45,840 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：15750 

时间：2017-06-20 14:53:02,657 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：32566 

时间：2017-06-20 14:53:03,966 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：33876 

时间：2017-06-20 14:53:04,572 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：34482 

时间：2017-06-20 14:53:04,793 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：34703 

时间：2017-06-20 14:53:05,317 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：35227 

时间：2017-06-20 14:53:38,745 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：4630 

时间：2017-06-20 14:53:54,932 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：20817 

时间：2017-06-20 14:55:53,450 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：139334 

时间：2017-06-20 14:55:58,271 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：144155 

时间：2017-06-20 14:56:00,257 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T用户登陆超时)","code":"T用户登陆超时"} 
时间：146141 

时间：2017-06-20 14:56:17,284 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T用户登陆超时)","code":"T用户登陆超时"} 
时间：163168 

时间：2017-06-20 14:56:21,523 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：167407 

时间：2017-06-20 15:00:16,948 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":" ","code":"0x0022"} 
时间：22635 

时间：2017-06-20 15:01:09,020 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0007"} 
时间：3050 

时间：2017-06-20 15:01:19,591 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0007"} 
时间：13621 

时间：2017-06-20 15:01:58,792 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0007"} 
时间：3704 

时间：2017-06-20 15:02:45,326 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0007"} 
时间：50237 

时间：2017-06-20 15:03:58,591 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0006"} 
时间：123502 

时间：2017-06-20 15:04:13,959 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：138871 

时间：2017-06-20 15:04:50,801 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：1458 

时间：2017-06-20 15:05:11,141 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：21799 

时间：2017-06-20 15:06:24,686 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：95344 

时间：2017-06-20 15:06:42,358 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：113015 

时间：2017-06-20 15:06:53,141 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：123799 

时间：2017-06-20 15:07:01,673 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：132330 

时间：2017-06-20 15:07:03,708 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：134366 

时间：2017-06-20 15:12:40,171 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：270 

时间：2017-06-20 15:12:49,809 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：9908 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:13:51,354 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：276 

时间：2017-06-20 15:14:01,363 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：10284 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:14:27,761 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：604 

时间：2017-06-20 15:15:02,002 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：34845 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:15:20,030 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：52873 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:15:44,140 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：76983 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:17:13,158 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：166001 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:20:09,611 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：342454 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:20:17,435 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：350278 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:20:48,447 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：381290 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:22:29,173 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：5884 

时间：2017-06-20 15:23:08,172 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：44884 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:23:44,649 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：81360 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:23:53,560 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：90271 
System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.App.Views.mgr.main.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:24:02,513 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：99224 
System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:24:06,798 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：103509 
System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.App.Views.mgr.question.edit.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:24:07,444 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：104156 
System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:24:21,839 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：118550 
System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict()
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:24:45,676 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：3723 
System.ArgumentNullException: 值不能为 null。
参数名: String
   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   在 System.Int32.Parse(String s)
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:29:38,116 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：2531 

时间：2017-06-20 15:30:00,194 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：24609 
System.InvalidCastException: 指定的转换无效。
   在 X.Core.Cache.WebCache.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\WebCache.cs:行号 33
   在 X.Core.Cache.CacheHelper.Get[T](String key) 位置 D:\Pro\x.xue\src\Xc\Core\Cache\CacheHelper.cs:行号 47
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\xmg.cs:行号 24
   在 X.App.Views.mgr.main.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\main.cs:行号 21
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 15:31:31,623 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：2538 

时间：2017-06-20 15:32:50,899 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：12883 

时间：2017-06-20 16:07:14,807 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：388 

时间：2017-06-20 16:16:16,832 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：306 

时间：2017-06-20 16:16:30,552 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：14026 
System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   在 X.App.Views.mgr.main.InitDict() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\mgr\main.cs:行号 32
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 16:16:49,653 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：300 

时间：2017-06-20 16:17:56,187 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：423 

时间：2017-06-20 17:05:48,822 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：229884 
NVelocity.Exception.ParseErrorException: Encountered "]-" at line 53, column 98.
Was expecting one of:
    "}" ...
    <DOT> ...
    "(" ...
     ---> NVelocity.Runtime.Parser.ParseException: Encountered "]-" at line 53, column 98.
Was expecting one of:
    "}" ...
    <DOT> ...
    "(" ...
    
   在 NVelocity.Runtime.Parser.Parser.Parse(TextReader reader, String templateName)
   在 NVelocity.Runtime.RuntimeInstance.Parse(TextReader reader, String templateName, Boolean dumpNamespace)
   在 NVelocity.Runtime.RuntimeInstance.Parse(TextReader reader, String templateName)
   在 NVelocity.Template.Process()
   --- 内部异常堆栈跟踪的结尾 ---
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 108
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 17:10:41,517 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：369 
System.NotSupportedException: 方法“System.String ToString(System.String)”不支持转换为 SQL。
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 108
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 17:17:25,469 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：383739 

时间：2017-06-20 17:23:18,247 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T试卷不存在)","code":"T试卷不存在"} 
时间：736517 

时间：2017-06-20 17:23:57,347 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T试卷不存在)","code":"T试卷不存在"} 
时间：775617 

时间：2017-06-20 17:25:27,988 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T试卷不存在)","code":"T试卷不存在"} 
时间：22750 

时间：2017-06-20 17:25:43,075 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(T试卷不存在)","code":"T试卷不存在"} 
时间：37837 

时间：2017-06-20 17:31:46,857 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：182777 
NVelocity.Exception.ParseErrorException: Encountered "#else\r\n" at line 106, column 21.
Was expecting one of:
    "(" ...
    <RPAREN> ...
    <ESCAPE_DIRECTIVE> ...
    <SET_DIRECTIVE> ...
    "\\\\" ...
    "\\" ...
    <TEXT> ...
    <SINGLE_LINE_COMMENT> ...
    "*#" ...
    "*#" ...
    <STRING_LITERAL> ...
    <END> ...
    "if" ...
    "stop" ...
    <NUMBER_LITERAL> ...
    <WORD> ...
    <IDENTIFIER> ...
    <DOT> ...
    "{" ...
    "}" ...
     ---> NVelocity.Runtime.Parser.ParseException: Encountered "#else\r\n" at line 106, column 21.
Was expecting one of:
    "(" ...
    <RPAREN> ...
    <ESCAPE_DIRECTIVE> ...
    <SET_DIRECTIVE> ...
    "\\\\" ...
    "\\" ...
    <TEXT> ...
    <SINGLE_LINE_COMMENT> ...
    "*#" ...
    "*#" ...
    <STRING_LITERAL> ...
    <END> ...
    "if" ...
    "stop" ...
    <NUMBER_LITERAL> ...
    <WORD> ...
    <IDENTIFIER> ...
    <DOT> ...
    "{" ...
    "}" ...
    
   在 NVelocity.Runtime.Parser.Parser.Parse(TextReader reader, String templateName)
   在 NVelocity.Runtime.RuntimeInstance.Parse(TextReader reader, String templateName, Boolean dumpNamespace)
   在 NVelocity.Runtime.RuntimeInstance.Parse(TextReader reader, String templateName)
   在 NVelocity.Template.Process()
   --- 内部异常堆栈跟踪的结尾 ---
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 108
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 17:33:29,117 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：285037 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.Table`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   在 System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   在 X.App.Views._web.InitView() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\_web.cs:行号 31
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 94
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

时间：2017-06-20 17:47:13,201 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:71) - 
错误：致命错误 
时间：23725 
System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 68
   在 X.App.Views._web.getSubject(Int32 age) 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\_web.cs:行号 0
   在 X.App.Views._web.InitView() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\_web.cs:行号 0
   在 X.App.Views.login.InitView() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\login.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 94
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31

时间：2017-06-20 17:47:22,494 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\x.xue\src\Xc\Core\Plugin\Loger.cs:71) - 
错误：致命错误 
时间：33019 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 D:\Pro\x.xue\src\Xc\Data\DataClasses.cs:行号 68
   在 X.Web.XFace.GetDict(String code, String val) 位置 D:\Pro\x.xue\src\Web\X.Web\XFace.cs:行号 0
   在 X.App.Views._web.InitView() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\_web.cs:行号 0
   在 X.App.Views.login.InitView() 位置 D:\Pro\x.xue\src\Web\Xue\X.App\Views\login.cs:行号 25
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.xue\src\Web\X.Web\Views\View.cs:行号 94
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.xue\src\Web\X.Web\XApp.cs:行号 31
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
